nvidia: beautify pre-install script

diff --git a/nvidia/pre-install b/nvidia/pre-install
--- a/nvidia/pre-install
+++ b/nvidia/pre-install
@@ -1,8 +1,9 @@
-#!/bin/sh
+#!/bin/sh -ex
+export PATH="/sbin:/usr/sbin:/bin:/usr/bin"
 
 # check for root privileges needed for gl-select
-if [ ! "$(id -u)" -eq 0 ]; then
-	echo "root privileges needed to run this pre-install script!"
+if [ "$(id -u)" != 0 ]; then
+	echo >&2 "$0: error: pre-install script requires superuser privilege"
 	exit 1
 fi
 
